jenkins build stage added

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -3,24 +3,28 @@ pipeline {
 
     stages { 
         stage('Build') {
-            agent{
-                docker{
+            agent {
+                docker {
                     image 'node:18-alpine'
                     reuseNode true
+                    args '-v /tmp/npm-cache:/root/.npm' // Cache npm modules
                 }
             }
             steps { 
-                 sh '''
-                 ls -la
-                 node --version 
-                 npm --version
-                 npm ci
-                 npm run build
-                 la -la
-                 '''
+                sh '''
+                set -e  # Exit on any command failure
+                echo "Cleaning npm cache and removing node_modules..."
+                rm -rf node_modules package-lock.json # Clean previous installs if they exist
+                npm cache clean --force # Clear the npm cache
+                
+                echo "Installing npm..."
+                npm ci --loglevel=verbose # Install dependencies
+                npm run build --loglevel=verbose # Build the project
+                
+                echo "Listing files after build..."
+                ls -la
+                '''
             }
         }
-        
-         
     }
 }
